sudo: required
dist: trusty

language: ruby
rvm:
  - 2.2.3

cache:
  bundler: true
  directories:
    - node_modules

env:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="6"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g writewell

script:
  - script/writewell
  - script/cibuild
  - npm test
