# For Atom Feed
domain: services.github.com
author: GitHub, Inc.
email: services@github.com


# Site Settings
locale                   : "en-US"
# Keep original, do not replace
title                    : "On Demand Training"
title_separator          : "-"
name                     : "GitHub, Inc."
description              : "You're in control. We're with you along the way."
baseurl                  : "/on-demand" # the subpath of your site, e.g. "/blog"
gh_repo                  :
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"




analytics:
  provider               : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-80557370-2

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# standard jekyll configuration

parentsite: https://services.github.com
permalink: /articles/:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

collections:
  modules:
    output: true
  courses:
    output: true

include:
- _stylesheets
- _javascript
sass:
  load_paths:
    - assets/_scss
    - node_modules
  style: :compressed

# Custom site configuration
lang: en

defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
